### ISSUE TITLE
Removing output files of failed job split_bam since they might be corrupted: bam_bundles

### ISSUE THREAD

**Issue by Cynthia-Swift** [nanoporetech/pipeline-nanopore-ref-isoforms#14]
Hi, I tried to run pipeline-nanopore-ref-isoforms both on test data and Drosophila_melanogaster data, but the pipeline is failing.
shell: snakemake --use-conda -j 5 all 
The error information:
_Error in rule split_bam:
    jobid: 5
    output: bam_bundles
    conda-env: /user/pipeline-nanopore-ref-isoforms/evaluation/pipeline-nanopore-ref-isoforms/.snakemake/conda/183daf34
    shell:
        
    if [ NO != "YES" ]
    then
        seqkit bam -j 5 -N 50000 alignments/reads_aln_sorted.bam -o bam_bundles
    else
        mkdir -p bam_bundles
        ln -s alignments/reads_aln_sorted.bam bam_bundles/000000000_ALL:0:1_bundle.bam
    fi
    
Removing output files of failed job split_bam since they might be corrupted:
bam_bundles
exception calling callback for <Future at 0x7fa47ece79e8 state=finished returned NoneType>
Traceback (most recent call last):
  File "/user/miniconda3/envs/pipeline-nanopore-ref-isoforms/lib/python3.6/site-packages/snakemake/executors.py", line 360, in _callback
    callback(job)
  File "/user/miniconda3/envs/pipeline-nanopore-ref-isoforms/lib/python3.6/site-packages/snakemake/scheduler.py", line 338, in _proceed
    self.progress()
  File "/user/miniconda3/envs/pipeline-nanopore-ref-isoforms/lib/python3.6/site-packages/snakemake/scheduler.py", line 477, in progress
    logger.progress(done=self.finished_jobs, total=len(self.dag))
  File "/user/miniconda3/envs/pipeline-nanopore-ref-isoforms/lib/python3.6/site-packages/snakemake/logging.py", line 160, in progress
    self.handler(dict(level="progress", done=done, total=total))
  File "/user/miniconda3/envs/pipeline-nanopore-ref-isoforms/lib/python3.6/site-packages/snakemake/logging.py", line 125, in handler
    handler(msg)
  File "/user/miniconda3/envs/pipeline-nanopore-ref-isoforms/lib/python3.6/site-packages/snakemake/logging.py", line 316, in text_handler
    p = done / total
ZeroDivisionError: division by zero

Traceback (most recent call last):
  File "/user/miniconda3/envs/pipeline-nanopore-ref-isoforms/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/user/miniconda3/envs/pipeline-nanopore-ref-isoforms/lib/python3.6/site-packages/snakemake/executors.py", line 371, in _callback
    error_callback(job)
  File "/user/miniconda3/envs/pipeline-nanopore-ref-isoforms/lib/python3.6/site-packages/snakemake/scheduler.py", line 346, in _error
    self._handle_error(job)
  File "/user/miniconda3/envs/pipeline-nanopore-ref-isoforms/lib/python3.6/site-packages/snakemake/scheduler.py", line 356, in _handle_error
    self.running.remove(job)
KeyError: split_bam_

Except the above problem that I cannot resolve, I also found some bugs in the Snakefile and scripts.
Firstly, conda can't install some dependences.
Error information:
_File "/user/pipeline-nanopore-ref-isoforms/scripts/run_fastq_qc.py", line 6, in <module>
    from pysam import FastxFile
ModuleNotFoundError: No module named 'pysam'_

I already used snakemake to install other nanotech tool and it works. So, I thought the process of installing snakemake is fine. And I changed the pipeline env.yml file to make conda to install the dependencies.
Here is the snakemake's environmental.ymal:
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::snakemake-minimal =5.4.5
  - python =3.6
  - jinja2 =2.10
  - networkx =2.1
  - matplotlib =2.2.3
  - graphviz =2.38.0
  - bcftools =1.9
  - samtools =1.9
  - bwa =0.7.17
  - pysam =0.15.0
pipeline's env.yml:
channels:
    - bsipos
    - conda-forge
    - bioconda
dependencies:
    - minimap2
    - samtools
    - bedtools
    - pychopper
    - pandas
    - seaborn
    - requests
    - gffread
    - seqkit_bsipos
    - csvtk
    - stringtie==2.1.1
    - gffcompare
    - curl
    - hmmer
    - spoa==3.4.0
##I copyed the dependencies of environmental.ymal to env.yml:
channels:
    - bsipos
    - conda-forge
    - bioconda
dependencies:
    - bioconda::snakemake-minimal =5.4.5
    - python =3.6
    - jinja2 =2.10
    - networkx =2.1
    - matplotlib =2.2.3
    - graphviz =2.38.0
    - bcftools =1.9
    - samtools =1.9
    - bwa =0.7.17
    - pysam =0.15.0
    - minimap2
    - samtools
    - bedtools
    - pychopper
    - pandas
    - seaborn
    - requests
    - gffread
    - seqkit_bsipos
    - csvtk
    - stringtie==2.1.1
    - gffcompare
    - curl
    - hmmer
    - spoa==3.4.0
And the "pysam" problem was settled.

Secondly, 
I fixed bugs in the Snakefile rule generate_fq_stats:
 shell:"""
        {SNAKEDIR}/scripts/run_fastq_qc.py --fastq {input.fastq} --output "processed_reads'
    """
##convert to
 shell:"""
        {SNAKEDIR}/scripts/run_fastq_qc.py --fastq {input.fastq} --output "processed_reads"
    """
Error information:
_Traceback (most recent call last):
  File "../../scripts/run_fastq_qc.py", line 52, in <module>
    main(args=parse_args())
  File "../../scripts/run_fastq_qc.py", line 48, in main
    run_fastq_qc(fastq_path=args.fastq, output=args.output_dir)
  File "../../scripts/run_fastq_qc.py", line 35, in run_fastq_qc
    with open(os.path.join(output, "base_qual.txt")) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'processed_reads/base_qual.txt'_

And the bug of scripts/run_fastq_qc.py:
    with open(os.path.join(output, "base_qual.txt")) as f:
        f.write("\n".join((str(q) for q in qualities)))
    with open(os.path.join(output, "read_qual.txt")) as f:
        f.write("\n".join((str(q) for q in mean_qualities)))
    with open(os.path.join(output, "lengths.txt")) as f:
        f.write("\n".join((str(l) for l in lengths)))
##convert to
    with open(os.path.join(output, "base_qual.txt"),"w") as f:
        f.write("\n".join((str(q) for q in qualities)))
    with open(os.path.join(output, "read_qual.txt"),"w") as f:
        f.write("\n".join((str(q) for q in mean_qualities)))
    with open(os.path.join(output, "lengths.txt"),"w") as f:
        f.write("\n".join((str(l) for l in lengths)))
And the rule generate_fq_stats works.

Thirdly, I tried to use the parameter "some" instead "all".
shell: snakemake --use-conda -j 5 some
The pipeline can output the results, but those files are somewhat different form the reference results.
So back to the first question, I infer that Snakefile' checkpoint rule may have some bugs and I cannot fixed them. Could you tell me what I can do to resolve the "Removing output files of failed job split_bam since they might be corrupted: bam_bundles"?

**Comment by bsipos** [comment]
Thanks for the bug reports! Could you please try again with the latest commit?

**Comment by Cynthia-Swift** [comment]
Thanks for your reply! I tried the latest commit and I saw the same error:
Error in rule split_bam:
    jobid: 5
    output: bam_bundles
    conda-env: /user/pipeline-nanopore-ref-isoforms/evaluation/pipeline-nanopore-ref-isoforms/.snakemake/conda/26b36a7f
    shell:
        
    if [ NO != "YES" ]
    then
        seqkit bam -j 5 -N 50000 alignments/reads_aln_sorted.bam -o bam_bundles
    else
        mkdir -p bam_bundles
        ln -s alignments/reads_aln_sorted.bam bam_bundles/000000000_ALL:0:1_bundle.bam
    fi
    
Removing output files of failed job split_bam since they might be corrupted:
bam_bundles
exception calling callback for <Future at 0x7f8f6779ffd0 state=finished returned NoneType>
Traceback (most recent call last):
  File "/user/miniconda3/envs/nanopore-ref-isoforms/lib/python3.6/site-packages/snakemake/executors.py", line 360, in _callback
    callback(job)
  File "/user/miniconda3/envs/nanopore-ref-isoforms/lib/python3.6/site-packages/snakemake/scheduler.py", line 338, in _proceed
    self.progress()
  File "/user/miniconda3/envs/nanopore-ref-isoforms/lib/python3.6/site-packages/snakemake/scheduler.py", line 477, in progress
    logger.progress(done=self.finished_jobs, total=len(self.dag))
  File "/user/miniconda3/envs/nanopore-ref-isoforms/lib/python3.6/site-packages/snakemake/logging.py", line 160, in progress
    self.handler(dict(level="progress", done=done, total=total))
  File "/user/miniconda3/envs/nanopore-ref-isoforms/lib/python3.6/site-packages/snakemake/logging.py", line 125, in handler
    handler(msg)
  File "/user/miniconda3/envs/nanopore-ref-isoforms/lib/python3.6/site-packages/snakemake/logging.py", line 316, in text_handler
    p = done / total
ZeroDivisionError: division by zero
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/user/miniconda3/envs/nanopore-ref-isoforms/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/user/miniconda3/envs/nanopore-ref-isoforms/lib/python3.6/site-packages/snakemake/executors.py", line 371, in _callback
    error_callback(job)
  File "/user/miniconda3/envs/nanopore-ref-isoforms/lib/python3.6/site-packages/snakemake/scheduler.py", line 346, in _error
    self._handle_error(job)
  File "/user/miniconda3/envs/nanopore-ref-isoforms/lib/python3.6/site-packages/snakemake/scheduler.py", line 356, in _handle_error
    self.running.remove(job)
KeyError: split_bam

**Comment by bsipos** [comment]
Hello!

This looks like a snakemake issue to me, so I suggest you ask around the appropriate support forum. If you still have issues please provide a small reproducible example to help diagnosing this issue.
